version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # Changed volume mapping
    environment:
      - CHROMA_HOST=db
      - CHROMA_PORT=8000
      # - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./frontend/src:/app/src
  db:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

volumes:
  chroma_data: